// Chamando a função alert
// alert("HELLO WORLD")

// Chamando o método log()
// console.log("Olá Arthur")

// Declaração da função - Ensinando o computador
// function bemVindo(nome) {
    // console.log("Bem Vindo" + nome)
// }

// let retorno = bemVindo()
// bemVindo("Tadeu")

// function somar(num1, num2) {
    // return num1 + num2;
// }

// let resultado = somar(6, 5)

// function Média(nota1, nota2, nota3) {
//     let somaNotas = nota1 + nota2 + nota3

//     let media = somaNotas / 3

//     console.log(media)
// }