// for - Loop Contado

// prompt("Digite o nome de um aluno")

// for(let contador = 0; contador < 5; contador++) {
    // prompt("Digite o nome de um aluno")
// }

// for(let cont= 10; cont >= 0; cont--) {
//     console.log(cont)
// }


// While - Loop condicional

// let opcao = prompt("Digite uma opção")

// while (opcao != "0") {
    // console.log("Repetiu")

    // opcao
// }

// console.log("Saiu")

// let contador = 0

// while(contador <= 5) {
//     console.log(contador);
//     contador+=1
// }


// do - while -> Loop condicional

// let contador = 0;

// do {
//     console.log(contador);
//     contador+=1
// } while (contador <= 5)

// do {
//     let valor = prompt("Digite um número: ")
//     switch (valor) {
//         case "1":
//             console.log("Você digitou o valor 1")
//             break;
//         case "2":
//             console.log("Você digitou o valor 2")
//             break;
//         case "3":
//             console.log("Você digitou o valor 3")
//             break;
//         default:
//             console.log("valor invalido")
//             break;
//     }
// } while (valor == "0")

// let num2 = 0;

// do {
//     console.log(num2);
//     num+=1
// } while (num2 < 10)

// forEach(Para cada) - percorrer a lista

// let num = [1,2,3,4,5,6,7]

// // num.forEach(elemento => {
// //     console.log("O número é: " + elemento)
// // })

// for(let elemento of num) {
//     console.log()
// }